using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataLink_ALA.DomainAbstractions
{
    //TODO: add summary and code

    /// <summary>
    /// An event generated by the system after all wiring and initialization is complete
    /// 
    /// IEvent
    /// </summary>
 
    class StartEvent
    {
    }
}
